---

- name: restart the system
  listen: request_reboot
  shell: "(sleep 5 ; reboot) &"
  async: 1
  poll: 0

- name: wait for the system to reboot
  listen: request_reboot
  wait_for_connection:
     connect_timeout: 20
     sleep: 5
     delay: 5
     timeout: 180
