---
- name: Kill wallet
  hosts: rewallet
  gather_facts: no
  become: yes
  tasks:
    - name: stop zend service
      systemd:
        state: stopped
        name: zend
    - name: wait for service to stop
      wait_for:
        delay: 10
    - name: copy updated tracker files
      file:
        path: /home/zen/.zen/wallet.dat
        state: absent

