---
- name: Upgrade zen daemon service
  hosts: zen:hf1_nodes
  gather_facts: no
  become: yes
  vars:
    deb_file: /home/nladmin/zen_3.3.1_amd64.deb
  tasks:
    - name: copy updated zend deb package
      copy:
        src: "{{ deb_file }}"
        dest: "{{ deb_file }}"

    - name: Install updated zend package
      apt:
        deb: "{{ deb_file }}"
        update_cache: no

    - name: Restart zend service
      systemd:
        name: zend
        state: restarted
